---
- name: Update and upgrade Debian systems
  hosts: all
  become: yes
  vars:
    discord_webhook: "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN"
    discord_message: "Server {{ inventory_hostname }} requires reboot after updates"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Check if upgrades are available
      apt:
        upgrade: safe
        autoremove: yes
        check_mode: yes
      register: apt_upgrade

    - name: Apply security upgrades if available
      apt:
        upgrade: safe
        autoremove: yes
      when: apt_upgrade.changed

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Post to Discord if reboot is needed
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: "{{ discord_message }}"
      when: reboot_required.stat.exists
